#!/bin/bash

# Populates each project folder with a copy of the 'common' folder
# which contains generic tools for new containers

for dir1 in $(ls); do
  if [ -d ${dir1} ] && [ "${dir1}" != "common" ]; then
    for dir2 in $(ls ${dir1}); do
       cp ./common ${dir1}/${dir2} -fr
       cp ../keyring ${dir1}/${dir2}/common/keys -fr
    done
  fi
done
