#!/bin/bash

# Create a non-privileged user account for testing
# and a root priv user for ansible management

swname="swuser"
swdir="/home/${swuser}"

groupadd -r $swname -g 433
useradd -u 431 -r -g ${swname} -d ${swdir} -s /sbin/nologin -c "non-priv user" ${swname}
chown -R ${swname}:${swname} ${swdir}

rootname="rootuser"
rootdir="/home/${rootname}"

mkdir ${rootdir}
useradd -d ${rootdir} -c "root user" ${rootname}
chown -R ${rootname}:${rootname} ${rootdir}

