#!/bin/bash

# Create a non-privileged user account for testing
# and a root priv user for ansible management

swname="swuser"
swdir="/home/${swuser}"

groupadd -r $username -g 433
useradd -u 431 -r -g ${username} -d ${homedir} -s /sbin/nologin -c "non-priv user" ${username}
chown -R ${swname}:${swname} .

rootname="rootuser"
rootdir="/home/${rootname}"

useradd -g ${rootname} -d ${homedir} -s /bin/bash -c "root user" ${rootname}
chown -R ${rootname}:${rootname}
usermod -g wheel ${rootuser}

