#!/bin/bash

# Setup the debian repo for cassandra from
# DataStax, install their public key,
# update apt and install

echo "deb http://debian.datastax.com/community stable main" | sudo tee -a /etc/apt/sources.list.d/cassandra.sources.list
curl -L http://debian.datastax.com/debian/repo_key | sudo apt-key add -

apt-get update
apt-get install -y dsc20=2.0.11-1 cassandra=2.0.11
apt-get clean

service cassandra stop
rm -rf /var/lib/cassandra/data/system/*
service cassandra start
